# Generated by Django 5.1.5 on 2025-02-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company_department_positions_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
