# Generated by Django 5.1.5 on 2025-02-05 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=120)),
                ('permission_description', models.TextField()),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rolesuser')),
            ],
        ),
    ]
