# Generated by Django 5.1.5 on 2025-02-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'АКТИВЕН'), ('fired', 'УВОЛЕН')], max_length=50, null=True),
        ),
    ]
