# Generated by Django 5.1.5 on 2025-02-10 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_historicaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='role_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.rolesuser'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rolesuser'),
        ),
    ]
