# Generated by Django 5.1.5 on 2025-02-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_historicaluser_role_user_user_role_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name_plural': 'Positions'},
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='background_profile_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='background_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
