# Generated by Django 5.1.5 on 2025-02-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_company_options_alter_positions_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name_plural': 'users'},
        ),
    ]
