# Generated by Django 5.1.5 on 2025-02-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0013_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesuser',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
    ]
