# Generated by Django 5.1.5 on 2025-02-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rolesuser_permissions_delete_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='deacivate',
            field=models.BooleanField(default=False),
        ),
    ]
