# Generated by Django 5.1.5 on 2025-02-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_department_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='department',
            managers=[
            ],
        ),
    ]
