# Generated by Django 5.1.5 on 2025-02-17 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_company_director_alter_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='position_name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='users.positions'),
        ),
    ]
