# Generated by Django 5.1.5 on 2025-02-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0021_remove_rolesuser_permissions_rolesuser_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolesuser',
            name='permissions',
        ),
        migrations.AddField(
            model_name='rolesuser',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
