# Generated by Django 5.1.5 on 2025-02-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0022_remove_rolesuser_permissions_rolesuser_permissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RolesUser',
            new_name='Roles',
        ),
    ]
