# Generated by Django 5.1.6 on 2025-02-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrafanaDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dashboard_uid', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
