# Generated by Django 5.1.6 on 2025-02-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_grafanadashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafanadashboard',
            name='panel_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
