# Generated by Django 5.1.6 on 2025-03-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_grafanadashboard_panel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='Users_background_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Users_avatar'),
        ),
    ]
