# Generated by Django 5.1.6 on 2025-03-15 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_user_background_profile_image_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
