# Generated by Django 5.1.6 on 2025-03-15 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_department_department_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_head_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_head',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
