# Generated by Django 5.1.6 on 2025-03-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_department_department_head_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_head_name',
        ),
    ]
