# Generated by Django 5.1.6 on 2025-04-01 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_historicaluser_email_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='users.department'),
        ),
    ]
