# Generated by Django 5.1.6 on 2025-04-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_positions_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
