# Generated by Django 5.1.6 on 2025-04-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_roles_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_owner',
        ),
    ]
