# Generated by Django 5.1.6 on 2025-04-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_remove_historicaluser_is_owner_remove_user_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_with_access',
            field=models.ManyToManyField(blank=True, related_name='accesible_by', to='users.department'),
        ),
    ]
