# Generated by Django 5.1.6 on 2025-04-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_department_department_with_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_user',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='role_user',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
