version: "3.9"

services:
  db:
    image: postgres:17
    container_name: taskmanager_db
    restart: always
    env_file:
      - taskmanager/.env  # Загружаем переменные из .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: taskmanager_app
    env_file:
      - taskmanager/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
