# Generated by Django 5.1.5 on 2025-02-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_historicalnews_historicalnews_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalnews',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical news', 'verbose_name_plural': 'historical News'},
        ),
        migrations.AlterModelOptions(
            name='historicalnews_comments',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical news_comments', 'verbose_name_plural': 'historical News Comments'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='news_comments',
            options={'verbose_name_plural': 'News Comments'},
        ),
    ]
