# Generated by Django 5.1.5 on 2025-02-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_historicalnews_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnews',
            name='tags',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
