# Generated by Django 5.1.5 on 2025-02-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_historicalnews_tags_news_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnews',
            name='documents',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
