# Generated by Django 5.1.5 on 2025-02-11 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_historicalnews_documents_news_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='HistoricalNews_comments',
            new_name='HistoricalNewsComment',
        ),
        migrations.AlterModelOptions(
            name='historicalnewscomment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical news comment', 'verbose_name_plural': 'historical News Comments'},
        ),
        migrations.RenameField(
            model_name='historicalnewscomment',
            old_name='news_id',
            new_name='news',
        ),
        migrations.RenameField(
            model_name='historicalnewscomment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='historicalnews',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'News Comments',
            },
        ),
        migrations.DeleteModel(
            name='News_comments',
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news', to='news.tag'),
        ),
    ]
