# Generated by Django 5.1.5 on 2025-02-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnews',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
