# Generated by Django 5.1.5 on 2025-03-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_historicalnews_content_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='news', to='news.tag'),
        ),
    ]
