# Generated by Django 5.1.6 on 2025-03-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnews',
            name='picture',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
