# Generated by Django 5.1.5 on 2025-02-06 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='sent_by',
        ),
    ]
