# Generated by Django 5.1.5 on 2025-02-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_historicalmessagehistory_historicalmessages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmessagehistory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical message history', 'verbose_name_plural': 'historical Message Histories'},
        ),
        migrations.AlterModelOptions(
            name='historicalmessages',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical messages', 'verbose_name_plural': 'historical Messages'},
        ),
        migrations.AlterModelOptions(
            name='messagehistory',
            options={'verbose_name_plural': 'Message Histories'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name_plural': 'Messages'},
        ),
    ]
