# Generated by Django 5.1.5 on 2025-02-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_historicalmessagehistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagehistory',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='messagehistory',
            name='sender_id',
        ),
        migrations.DeleteModel(
            name='HistoricalMessageHistory',
        ),
        migrations.DeleteModel(
            name='MessageHistory',
        ),
    ]
