# Generated by Django 5.1.5 on 2025-02-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_messagehistory_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmessages',
            name='message_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
