# Generated by Django 5.1.5 on 2025-02-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0003_historicalevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
