# Generated by Django 5.1.6 on 2025-02-24 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0004_alter_event_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='historicalevent',
            old_name='user_id',
            new_name='user',
        ),
    ]
