# Generated by Django 5.1.5 on 2025-02-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reports_department_id'),
        ('users', '0008_alter_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='department_id',
        ),
        migrations.AddField(
            model_name='reports',
            name='department',
            field=models.ManyToManyField(blank=True, to='users.department'),
        ),
    ]
