# Generated by Django 5.1.5 on 2025-02-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_reports_department_id_reports_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'verbose_name_plural': 'Reports'},
        ),
    ]
