# Generated by Django 5.1.5 on 2025-02-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_reports_options'),
        ('users', '0017_alter_department_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='reports', to='users.department'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
