# Generated by Django 5.1.5 on 2025-02-18 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0004_alter_event_description_and_more'),
        ('reports', '0005_alter_reports_department_alter_reports_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='event_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_calendar.event'),
        ),
    ]
