# Generated by Django 5.1.5 on 2025-02-18 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reports_event_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='event_report',
        ),
        migrations.AddField(
            model_name='reports',
            name='employees_report',
            field=models.ManyToManyField(blank=True, related_name='employees_report', to=settings.AUTH_USER_MODEL),
        ),
    ]
