# Generated by Django 5.1.5 on 2025-02-06 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_projects_departement'),
        ('users', '0007_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department'),
        ),
    ]
