# Generated by Django 5.1.5 on 2025-02-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_projects_project_id_alter_task_asigner_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='asigner_id',
            new_name='asigned_id',
        ),
    ]
