# Generated by Django 5.1.5 on 2025-02-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('АКТИВЕН', 'АКТИВЕН'), ('В ПРОЦЕССЕ', 'В ПРОЦЕССЕ'), ('ЗАКОНЧЕН', 'ЗАКОНЧЕН')], default='АКТИВЕН', max_length=100),
        ),
    ]
