# Generated by Django 5.1.5 on 2025-02-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project_id',
        ),
        migrations.AddField(
            model_name='task',
            name='project_id',
            field=models.ManyToManyField(blank=True, to='tasks.projects'),
        ),
    ]
