# Generated by Django 5.1.5 on 2025-02-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_task_project_id_task_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
