# Generated by Django 5.1.5 on 2025-02-06 11:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_task_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='taskcomments',
            new_name='Task_comments',
        ),
    ]
