# Generated by Django 5.1.5 on 2025-02-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_task_asigned_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='asigned_id',
            new_name='assigned_id',
        ),
    ]
