# Generated by Django 5.1.5 on 2025-02-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_rename_asigned_id_task_assigned_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='departement',
            new_name='department',
        ),
    ]
