# Generated by Django 5.1.5 on 2025-02-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_rename_departement_projects_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_id',
            new_name='asigned_id',
        ),
    ]
