# Generated by Django 5.1.5 on 2025-02-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_rename_asigned_id_task_asigned_id_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='asigned_id_id',
            new_name='assigned_id',
        ),
    ]
