# Generated by Django 5.1.5 on 2025-02-07 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_rename_asigned_id_id_task_assigned_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='department',
        ),
        migrations.RemoveField(
            model_name='task_comments',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='task_comments',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Task_comments',
        ),
    ]
