# Generated by Django 5.1.5 on 2025-02-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_historicalprojects_historicaltask_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltask',
            old_name='assigned_id',
            new_name='assigned',
        ),
        migrations.RenameField(
            model_name='historicaltask_comments',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='historicaltask_comments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assigned_id',
            new_name='assigned',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project_id',
            new_name='projects',
        ),
        migrations.RenameField(
            model_name='task_comments',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='task_comments',
            old_name='user_id',
            new_name='user',
        ),
    ]
