# Generated by Django 5.1.5 on 2025-02-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_rename_assigned_id_historicaltask_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
