# Generated by Django 5.1.5 on 2025-02-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_alter_historicaltask_tags_alter_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojects',
            name='project_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='status',
            field=models.CharField(choices=[('АКТИВЕН', 'АКТИВЕН'), ('В ПРОЦЕССЕ', 'В ПРОЦЕССЕ'), ('ЗАКОНЧЕН', 'ЗАКОНЧЕН')], db_index=True, default='АКТИВЕН', max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('АКТИВЕН', 'АКТИВЕН'), ('В ПРОЦЕССЕ', 'В ПРОЦЕССЕ'), ('ЗАКОНЧЕН', 'ЗАКОНЧЕН')], db_index=True, default='АКТИВЕН', max_length=100),
        ),
    ]
