# Generated by Django 5.1.5 on 2025-02-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_alter_historicalprojects_project_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprojects',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical projects', 'verbose_name_plural': 'historical Projects'},
        ),
        migrations.AlterModelOptions(
            name='historicaltask',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical task', 'verbose_name_plural': 'historical Task'},
        ),
        migrations.AlterModelOptions(
            name='historicaltask_comments',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical task_comments', 'verbose_name_plural': 'historical Task Comments'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'Task'},
        ),
        migrations.AlterModelOptions(
            name='task_comments',
            options={'verbose_name_plural': 'Task Comments'},
        ),
    ]
