# Generated by Django 5.1.5 on 2025-02-11 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_files_options'),
        ('tasks', '0027_alter_historicalprojects_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='files',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='files.files'),
        ),
        migrations.AddField(
            model_name='historicaltask_comments',
            name='files',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='files.files'),
        ),
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.files'),
        ),
        migrations.AddField(
            model_name='task_comments',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.files'),
        ),
    ]
