# Generated by Django 5.1.5 on 2025-02-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_alter_historicalprojects_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='documents',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaltask_comments',
            name='documents',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='task_comments',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
