# Generated by Django 5.1.5 on 2025-02-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_historicaltask_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojects',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
