# Generated by Django 5.1.5 on 2025-02-12 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_alter_historicalprojects_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='projects',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tasks.projects'),
        ),
        migrations.AlterField(
            model_name='historicalprojects',
            name='start_date',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='priority',
            field=models.CharField(choices=[('НИЗКИЙ', 'НИЗКИЙ'), ('СРЕДНИЙ', 'СРЕДНИЙ'), ('ВЫСОКИЙ', 'ВЫСОКИЙ'), ('КРИТИЧЕСКИЙ', 'КРИТИЧЕСКИЙ'), ('ТЕХНИЧЕСКИЙ ДОЛГ', 'ТЕХНИЧЕСКИЙ ДОЛГ')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='start_date',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='status',
            field=models.CharField(choices=[('АКТИВЕН', 'АКТИВЕН'), ('В ПРОЦЕССЕ', 'В ПРОЦЕССЕ'), ('ЗАКОНЧЕН', 'ЗАКОНЧЕН'), ('НЕ АКТИВЕН', 'НЕ АКТИВЕН'), ('К УДАЛЕНИЮ', 'К УДАЛЕНИЮ')], db_index=True, default='АКТИВЕН', max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('НИЗКИЙ', 'НИЗКИЙ'), ('СРЕДНИЙ', 'СРЕДНИЙ'), ('ВЫСОКИЙ', 'ВЫСОКИЙ'), ('КРИТИЧЕСКИЙ', 'КРИТИЧЕСКИЙ'), ('ТЕХНИЧЕСКИЙ ДОЛГ', 'ТЕХНИЧЕСКИЙ ДОЛГ')], max_length=100),
        ),
        migrations.RemoveField(
            model_name='task',
            name='projects',
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('АКТИВЕН', 'АКТИВЕН'), ('В ПРОЦЕССЕ', 'В ПРОЦЕССЕ'), ('ЗАКОНЧЕН', 'ЗАКОНЧЕН'), ('НЕ АКТИВЕН', 'НЕ АКТИВЕН'), ('К УДАЛЕНИЮ', 'К УДАЛЕНИЮ')], db_index=True, default='АКТИВЕН', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='projects',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tasks', to='tasks.projects'),
        ),
    ]
