# Generated by Django 5.1.6 on 2025-02-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_historicaltask_agreed_with_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltask',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
