# Generated by Django 5.1.6 on 2025-02-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_alter_priority_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltask',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
    ]
