# Generated by Django 5.1.6 on 2025-03-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_alter_historicaltask_comments_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
