# Generated by Django 5.1.6 on 2025-03-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_alter_historicaltask_end_date_alter_task_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='task_documents'),
        ),
    ]
