# Generated by Django 5.1.6 on 2025-03-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0041_alter_task_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
