# Generated by Django 5.1.6 on 2025-03-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0002_process_created_at_process_created_by_and_more'),
    ]

    operations = [
    ]
