# Generated by Django 5.1.6 on 2025-03-31 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0003_auto_20250331_2054'),
    ]

    operations = [
    ]
