# Generated by Django 5.1.6 on 2025-04-01 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0005_processstagetemplate_remove_process_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='bpm.process'),
        ),
    ]
