# Generated by Django 5.1.6 on 2025-04-01 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0007_alter_autotaskrule_source_department_and_more'),
        ('users', '0034_positions_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='responsible_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='users.positions'),
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.positions')),
                ('from_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='bpm.workflowstep')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='bpm.process')),
                ('to_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='bpm.workflowstep')),
            ],
        ),
    ]
