# Generated by Django 5.1.6 on 2025-04-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0008_workflowstep_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'permissions': [('start_process', 'Может запускать процесс'), ('approve_process', 'Может одобрять  процесс'), ('execute_process', 'Может выполнять  процесс'), ('finish_process', 'Может завершать  процесс')]},
        ),
    ]
