# Generated by Django 5.1.6 on 2025-04-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0009_alter_process_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
