# Generated by Django 5.1.6 on 2025-04-07 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0010_alter_dashboardwidget_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDepartmentRole',
        ),
    ]
