# Generated by Django 5.1.6 on 2025-04-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0011_delete_userdepartmentrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='position_x',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='position_y',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
