# Generated by Django 5.1.6 on 2025-04-10 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0012_alter_dashboardwidget_position_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstagetemplate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='bpm.processtemplate'),
        ),
    ]
