# Generated by Django 5.1.6 on 2025-04-10 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0014_alter_process_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstage',
            name='template_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bpm.processstagetemplate'),
        ),
    ]
