# Generated by Django 5.1.6 on 2025-04-10 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0015_alter_processstage_template_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowrule',
            name='from_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='bpm.processstage'),
        ),
        migrations.AlterField(
            model_name='workflowrule',
            name='to_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='bpm.processstage'),
        ),
        migrations.AddField(
            model_name='processstage',
            name='is_key_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='WorkflowStep',
        ),
    ]
