# Generated by Django 5.1.6 on 2025-04-14 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0016_alter_workflowrule_from_step_and_more'),
        ('users', '0038_remove_user_role_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('start_event', 'Начальное событие'), ('end_event', 'Конечное событие'), ('task', 'Задача')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('assigned_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.positions')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='bpm.process')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='bpm.processstage')),
            ],
        ),
        migrations.CreateModel(
            name='ElementConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='bpm.processelement')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='bpm.processelement')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершен'), ('terminated', 'Прерван')], default='active', max_length=20)),
                ('current_element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='bpm.processelement')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='bpm.process')),
            ],
        ),
    ]
