# Generated by Django 5.1.6 on 2025-04-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0017_processelement_elementconnection_processexecution'),
    ]

    operations = [
        migrations.CreateModel(
            name='BpmnXmlProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml', models.CharField()),
            ],
        ),
    ]
