# Generated by Django 5.1.6 on 2025-04-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0018_bpmnxmlprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpmnxmlprocess',
            name='xml',
            field=models.TextField(null=True),
        ),
    ]
