# Generated by Django 5.1.6 on 2025-04-15 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0019_alter_bpmnxmlprocess_xml'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='bpmn_xml',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='bpm.bpmnxmlprocess'),
        ),
    ]
