# Generated by Django 5.1.6 on 2025-04-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0020_process_bpmn_xml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpmnxmlprocess',
            name='xml',
            field=models.TextField(default='<?xml version="1.0" encoding="UTF-8"?> <bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" id="Definitions_1" targetNamespace="http://bpmn.io/schema/bpmn"> <bpmn:process id="Process_1" isExecutable="true"> </bpmn:process> <bpmndi:BPMNDiagram id="BPMNDiagram_1"> <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1"> </bpmndi:BPMNPlane> </bpmndi:BPMNDiagram> </bpmn:definitions>', null=True),
        ),
    ]
