# Generated by Django 5.1.6 on 2025-04-21 07:06

import bpm.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0022_alter_bpmnxmlprocess_xml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpmnxmlprocess',
            name='xml',
            field=models.TextField(default=bpm.models.empty_xml),
        ),
        migrations.AlterField(
            model_name='task',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='bpm.processstage'),
        ),
    ]
