# Generated by Django 5.1.6 on 2025-04-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0023_alter_bpmnxmlprocess_xml_alter_task_current_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='process',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='process',
            name='recurring_interval',
        ),
        migrations.RemoveField(
            model_name='process',
            name='template',
        ),
        migrations.RemoveField(
            model_name='task',
            name='current_stage',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent_task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AddField(
            model_name='task',
            name='return_reason',
            field=models.CharField(choices=[('incorrect_execution', 'Неправильное выполнение'), ('deadline_ignored', 'Нарушен срок выполнения'), ('not_what_was_requested', 'Сделано не то, что просили'), ('missing_data', 'Отсутствуют данные или документы'), ('approval_failed', 'Не прошло согласование'), ('incomplete_task', 'Задача выполнена не полностью')], default='incorrect_execution', max_length=50),
        ),
    ]
