# Generated by Django 5.1.6 on 2025-04-21 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0024_remove_process_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='current_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='bpm.task'),
        ),
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('completed', 'Завершён')], default='not_started', max_length=20),
        ),
    ]
