# Generated by Django 5.1.6 on 2025-04-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0026_remove_task_created_by_process_bpmn_process_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
    ]
