# Generated by Django 5.1.6 on 2025-04-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0027_remove_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
