# Generated by Django 5.1.6 on 2025-04-28 05:00

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0028_alter_task_completed_at_alter_task_return_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementconnection',
            name='source',
        ),
        migrations.RemoveField(
            model_name='elementconnection',
            name='target',
        ),
        migrations.RemoveField(
            model_name='processexecution',
            name='current_element',
        ),
        migrations.RemoveField(
            model_name='processexecution',
            name='process',
        ),
        migrations.RemoveField(
            model_name='processstage',
            name='process',
        ),
        migrations.RemoveField(
            model_name='processstage',
            name='template_stage',
        ),
        migrations.RemoveField(
            model_name='taskstagehistory',
            name='from_stage',
        ),
        migrations.RemoveField(
            model_name='workflowrule',
            name='from_step',
        ),
        migrations.RemoveField(
            model_name='workflowrule',
            name='to_step',
        ),
        migrations.RemoveField(
            model_name='processelement',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='taskstagehistory',
            name='to_stage',
        ),
        migrations.RemoveField(
            model_name='processstagetemplate',
            name='template',
        ),
        migrations.RemoveField(
            model_name='processtemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='processtemplate',
            name='department',
        ),
        migrations.RemoveField(
            model_name='taskstagehistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='taskstagehistory',
            name='task',
        ),
        migrations.RemoveField(
            model_name='workflowrule',
            name='allowed_position',
        ),
        migrations.RemoveField(
            model_name='workflowrule',
            name='process',
        ),
        migrations.RemoveField(
            model_name='processelement',
            name='assigned_role',
        ),
        migrations.RemoveField(
            model_name='processelement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='processelement',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='processelement',
            name='position_y',
        ),
        migrations.AddField(
            model_name='processelement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processelement',
            name='element_id',
            field=models.CharField(default=datetime.datetime(2025, 4, 28, 5, 0, 59, 820016, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processelement',
            name='next_element',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='processelement',
            name='element_type',
            field=models.CharField(choices=[('start_event', 'Начальное событие'), ('end_event', 'Конечное событие'), ('task', 'Задача'), ('parallel gateway', 'Параллельный шлюз')], max_length=20),
        ),
        migrations.AlterField(
            model_name='processelement',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='AutoTaskRule',
        ),
        migrations.DeleteModel(
            name='ElementConnection',
        ),
        migrations.DeleteModel(
            name='ProcessExecution',
        ),
        migrations.DeleteModel(
            name='ProcessStage',
        ),
        migrations.DeleteModel(
            name='ProcessStageTemplate',
        ),
        migrations.DeleteModel(
            name='ProcessTemplate',
        ),
        migrations.DeleteModel(
            name='TaskStageHistory',
        ),
        migrations.DeleteModel(
            name='WorkflowRule',
        ),
    ]
