# Generated by Django 5.1.6 on 2025-04-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0029_remove_elementconnection_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processelement',
            name='next_element',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
