# Generated by Django 5.1.6 on 2025-04-28 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0030_alter_processelement_next_element'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(default='sequenceFlow', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_element', to='bpm.processelement')),
                ('start_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_element', to='bpm.processelement')),
            ],
        ),
    ]
