# Generated by Django 5.1.6 on 2025-04-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0031_processlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processelement',
            name='element_type',
            field=models.CharField(choices=[('startEvent', 'Начальное событие'), ('endEvent', 'Конечное событие'), ('task', 'Задача'), ('parallelGateway', 'Параллельный шлюз')], max_length=20),
        ),
    ]
