# Generated by Django 5.1.6 on 2025-04-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0032_alter_processelement_element_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processelement',
            name='element_type',
            field=models.CharField(choices=[('startEvent', 'Начальное событие'), ('endEvent', 'Конечное событие'), ('task', 'Задача'), ('parallelGateway', 'И'), ('exclusiveGateway', 'ИЛИ')], max_length=20),
        ),
    ]
