# Generated by Django 5.1.6 on 2025-04-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0034_historicalnotification_historicalprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocess',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('completed', 'Завершён')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('completed', 'Завершён')], default='pending', max_length=20, null=True),
        ),
    ]
