# Generated by Django 5.1.6 on 2025-04-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0035_alter_historicalprocess_status_alter_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processelement',
            name='element_type',
            field=models.CharField(choices=[('startEvent', 'Начальное событие'), ('endEvent', 'Конечное событие'), ('task', 'Задача'), ('parallelGateway', 'И'), ('exclusiveGateway', 'ИЛИ'), ('sequenceFlow', 'Стрелка'), ('text', 'Комментарий'), ('textAnnotation', 'Текстовое примечание')], max_length=20),
        ),
    ]
