# Generated by Django 5.1.6 on 2025-04-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0036_alter_processelement_element_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='processelement',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
