# Generated by Django 5.1.6 on 2025-04-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0037_processelement_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processelement',
            old_name='comment',
            new_name='annotation',
        ),
        migrations.AddField(
            model_name='processelement',
            name='attributes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processelement',
            name='documentation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
