# Generated by Django 5.1.6 on 2025-04-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0038_rename_comment_processelement_annotation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processelement',
            name='next_element',
        ),
    ]
