# Generated by Django 5.1.6 on 2025-04-30 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0039_remove_processelement_next_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlink',
            name='process',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='bpm.process'),
            preserve_default=False,
        ),
    ]
