# Generated by Django 5.1.6 on 2025-05-05 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0040_processlink_process'),
        ('users', '0038_remove_user_role_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_department', to='users.department'),
        ),
    ]
