# Generated by Django 5.1.6 on 2025-05-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0041_task_assigned_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlink',
            name='condition_expression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processlink',
            name='source_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processlink',
            name='target_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
