# Generated by Django 5.1.6 on 2025-05-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0042_processlink_condition_expression_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processelement',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='processelement',
            name='documentation',
        ),
    ]
