# Generated by Django 5.1.6 on 2025-05-06 06:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0043_remove_processelement_attributes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='department',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='dashboard',
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='department',
        ),
        migrations.AddField(
            model_name='processelement',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GatewayCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(max_length=50)),
                ('condition_value', models.JSONField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='bpm.processelement')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='bpm.process')),
                ('target_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_targets', to='bpm.processelement')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершен')], default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='bpm.processelement')),
                ('parent_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpm.token')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='bpm.process')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalToken',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершен')], default='active', max_length=30)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('element', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bpm.processelement')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bpm.process')),
                ('parent_token', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bpm.token')),
            ],
            options={
                'verbose_name': 'historical token',
                'verbose_name_plural': 'historical tokens',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.DeleteModel(
            name='DashboardWidget',
        ),
    ]
