# Generated by Django 5.1.6 on 2025-05-06 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0045_processelement_assigned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprocess',
            name='current_task',
        ),
        migrations.RemoveField(
            model_name='process',
            name='current_task',
        ),
        migrations.AddField(
            model_name='process',
            name='active_tokens',
            field=models.ManyToManyField(blank=True, related_name='active_processes', to='bpm.token'),
        ),
        migrations.AddField(
            model_name='task',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='bpm.processelement'),
        ),
        migrations.AlterField(
            model_name='processelement',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
