# Generated by Django 5.1.6 on 2025-05-06 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0046_remove_historicalprocess_current_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='bpmn_task_id',
        ),
        migrations.AddField(
            model_name='gatewaycondition',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='processelement',
            name='element_type',
            field=models.CharField(choices=[('startEvent', 'Начальное событие'), ('endEvent', 'Конечное событие'), ('task', 'Задача'), ('parallelGateway', 'И'), ('exclusiveGateway', 'ИЛИ'), ('text', 'Комментарий'), ('textAnnotation', 'Текстовое примечание')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='processelement',
            index=models.Index(fields=['process', 'element_id'], name='bpm_process_process_87e360_idx'),
        ),
        migrations.AddIndex(
            model_name='processelement',
            index=models.Index(fields=['element_type'], name='bpm_process_element_8be299_idx'),
        ),
        migrations.AddIndex(
            model_name='processlink',
            index=models.Index(fields=['process', 'start_element', 'end_element'], name='bpm_process_process_bd7345_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['process', 'status'], name='bpm_token_process_febe78_idx'),
        ),
    ]
