# Generated by Django 5.1.6 on 2025-05-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpm', '0047_remove_task_bpmn_task_id_gatewaycondition_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bpmn_task_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
