# Generated by Django 5.1.5 on 2025-02-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ДЕНЬ РОЖДЕНИЕ', 'ДЕНЬ РОЖДЕНИЕ'), ('МЕРОПРИЯТИЕ', 'МЕРОПРИЯТИЕ'), ('ДОСТИЖЕНИЕ', 'ДОСТИЖЕНИЕ'), ('НАГРАДА', 'НАГРАДА')], max_length=100),
        ),
    ]
